# Image Edit Benchmark Configuration Template

# Benchmark数据集配置
benchmark:
  data_path: "/data2/yixuan/Benchmark/version_2_50_pair/version_2_with_imagesb64.json"  # benchmark数据集路径
  categories:  # 五大类别名称（按subset字段分类）
    - "物理"
    - "环境"
    - "社会"
    - "因果"
    - "指代"

# 扩散编辑模型配置
diffusion_model:
  type: "example_model"  # 模型类型: example_model, custom_model, 或自定义
  class_path: "src.models.diffusion.implementations.example_model.ExampleDiffusionModel"  # 模型类的完整路径
  params:
    model_name: "your-model-name"
    device: "cuda"
    batch_size: 1
    # 添加其他模型特定参数

# Reward评分模型配置
reward_model:
  type: "example_reward"  # 模型类型
  class_path: "src.models.reward.implementations.example_reward.ExampleRewardModel"  # 模型类的完整路径
  params:
    model_name: "your-reward-model-name"
    device: "cuda"
    temperature: 0.7
    # 添加其他模型特定参数

# Prompt配置 - 不同类别使用不同的评分prompt
prompts:
  category_1:
    system_prompt: "You are an expert image quality evaluator."
    user_prompt_template: |
      Original description: {original_description}
      Edit instruction: {edit_instruction}
      Please rate the edited image quality on a scale of 0-10.
  
  category_2:
    system_prompt: "You are an expert image quality evaluator."
    user_prompt_template: |
      Original description: {original_description}
      Edit instruction: {edit_instruction}
      Please rate the edited image quality on a scale of 0-10.
  
  category_3:
    system_prompt: "You are an expert image quality evaluator."
    user_prompt_template: |
      Original description: {original_description}
      Edit instruction: {edit_instruction}
      Please rate the edited image quality on a scale of 0-10.
  
  category_4:
    system_prompt: "You are an expert image quality evaluator."
    user_prompt_template: |
      Original description: {original_description}
      Edit instruction: {edit_instruction}
      Please rate the edited image quality on a scale of 0-10.
  
  category_5:
    system_prompt: "You are an expert image quality evaluator."
    user_prompt_template: |
      Original description: {original_description}
      Edit instruction: {edit_instruction}
      Please rate the edited image quality on a scale of 0-10.

# 评估配置
evaluation:
  save_generated_images: true  # 是否保存生成的图像
  output_dir: "outputs"
  results_dir: "outputs/results"
  images_dir: "outputs/images"
  logs_dir: "outputs/logs"
  
  # 是否启用断点续传
  resume_from_checkpoint: false
  checkpoint_path: "outputs/checkpoint.json"
  
  # 评分统计
  metrics:
    - "mean"
    - "std"
    - "median"
    - "min"
    - "max"

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  console_output: true
  file_output: true
  log_file: "outputs/logs/evaluation.log"

# 运行配置
runtime:
  num_workers: 1
  use_multiprocessing: false
  seed: 42

